### ISSUE TITLE
skip_pre isn't always respected

### ISSUE THREAD

**Issue by nikolas** [mozilla/bleach#179]
Here's a failing test for the issue I'm running into (PR #162)

```py
def test_skip_pre_with_code_element():
    """Skip linkification in <code> tags that occur in <pre> tags."""
    simple = 'http://xx.com <pre><code>http://xx.com</code></pre>'
    linked = ('<a href="http://xx.com" rel="nofollow">http://xx.com</a> '
              '<pre><code>http://xx.com</code></pre>')
    eq_(linked, linkify(simple, skip_pre=True))
```

I would expect `linked` and `linkify(simple, skip_pre=True)` to be equal - the `http://xx.com` inside the pre and code tags not getting linkified. However, this test fails like this:

```
FAIL: Skip linkification in <code> tags that occur in <pre> tags.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nik/.pyenv/versions/2.7.10/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nik/src/bleach/bleach/tests/test_links.py", line 322, in test_skip_pre_with_code_element
    eq_(linked, linkify(simple, skip_pre=True))
AssertionError: '<a href="http://xx.com" rel="nofollow">http://xx.com</a> <pre><code>http://xx.com</code></pre>' != u'<a href="http://xx.com" rel="nofollow">http://xx.com</a> <pre><code><a href="http://xx.com" rel="nofollow">http://xx.com</a></code></pre>'
```

**Comment by willkg** [comment]
Seems like the issue here is that `skip_pre=True` isn't covering the entire `<pre>`--only the topmost level of children. If that's true, I claim that's not correct behavior and is a bug.

I'll look into this at some point this month.

**Comment by willkg** [comment]
Oh, neato--this is covered by #150 already. Closing this out as a duplicate.
