### ISSUE TITLE
ImportError: No module named base (bleach==2.0.0, html5lib==1.0b8)

### ISSUE THREAD

**Issue by bastbnl** [mozilla/bleach#267]
Hi,

First of all, I'd like to thank you all for maintaining such a nice package. 

I updated bleach today to learn that it breaks with an `ImportError` when used within a Django project:
```
(env-brownpapersession)bastb@bastb-vps:/var/www/brownpapersession/dev/brownpapersession$ python manage.py shell
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/brownpapersession/dev/brownpapersession/invite/models.py", line 24, in <module>
    from app.util import build_then_send_message
  File "/var/www/brownpapersession/dev/brownpapersession/app/util.py", line 25, in <module>
    from bleach import clean
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/bleach/__init__.py", line 5, in <module>
    from bleach.linkifier import (
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/bleach/linkifier.py", line 5, in <module>
    from html5lib.filters.base import Filter
ImportError: No module named base
```

I didn't find updates to `html5lib`. I found a release note concerning a rewrite of `bleach.clean()`. Did I miss something?

I rolled back to version 1.5.0. 

Thanks!

**Comment by willkg** [comment]
html5lib 1.0b8 is equivalent to html5lib 0.9999999 (7 9s). You need to update to html5lib >= 0.99999999 (8 9s) which is 1.0b9 or later.

https://github.com/html5lib/html5lib-python/releases

You might need to explicitly upgrade html5lib to a supported version--it might not upgrade on its own because of the version numbers. In other words, pip probably thinks 1.0b8 comes *after* 0.99999999 (8 9s) which is not true.

Hope that helps!

**Comment by bastbnl** [comment]
I tried and failed, apparently due to another package this time. I'll look into it when I've got some time on my hands. 

For now, it looks like I will not be able to use a plain `requirements.txt` (pip freeze) to rebuild the virtual environment, possibly due to the way `pip` handles versions. Right?

**Comment by willkg** [comment]
You should be fine with a `requirements.txt` file. You just need to explicitly specify the html5lib version you want to install.

**Comment by bastbnl** [comment]
Got it! Thanks
