### ISSUE TITLE
ImportError: cannot import name viewkeys

### ISSUE THREAD

**Issue by fengallan0** [mozilla/bleach#287]
```
Traceback (most recent call last):
  File "/Users/shuhao/myproect/flask/manage.py", line 5, in <module>
    from app import  db, User, Role,create_app,Post
  File "/Users/shuhao/myproect/flask/app/__init__.py", line 24, in <module>
    from .models import User, Role,Post
  File "/Users/shuhao/myproect/flask/app/models.py", line 11, in <module>
    import bleach
  File "/Library/Python/2.7/site-packages/bleach/__init__.py", line 5, in <module>
    from bleach.linkifier import (
  File "/Library/Python/2.7/site-packages/bleach/linkifier.py", line 4, in <module>
    import html5lib
  File "/Library/Python/2.7/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/Library/Python/2.7/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

**Comment by willkg** [comment]
What version of bleach, html5lib, Python, and six are you using?

**Comment by fengallan0** [comment]
bleach 2.0.0
html5lib 1.0b10
six 1.10.0
when i use ‘import bleach’
The above error occurred
No solution was found, so call for help！

**Comment by willkg** [comment]
six 1.10.0 definitely has a `viewkeys`:

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> six.__version__
'1.10.0'
>>> from six import viewkeys
>>> 
```

I suspect the problem you're having is related to your Python environment.

Maybe the six that is being imported is not version 1.10.0? Maybe there's another module in your PYTHONPATH named "six"?

Are you using virtual environments? Maybe you need to activate your virtual environment before you run Flask?

**Comment by fengallan0** [comment]
Thank you very much！ It's pycharm, the virtual multi environment problem

**Comment by willkg** [comment]
It sounds like you're all set, so I'm going to close this out.
