### ISSUE TITLE
Hi, My use markdown_tags error

### ISSUE THREAD

**Issue by yika-aixi** [mozilla/bleach#365]
module 'bleach_whitelist' has no attribute 'markdown_tags'

Code:
```
import markdown
import bleach
import bleach_whitelist

def StrToMakrDown(str,makrClear = True):
	newStr = markdown.markdown(str)
	if makrClear:
		newStr = bleach.clean(newStr, bleach_whitelist.markdown_tags, bleach_whitelist.markdown_attrs)
	return newStr
```

Detail Errors:
```
Traceback (most recent call last):
  File "I:\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "I:\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "I:\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "I:\Icarus\Icarus-website\Site\views.py", line 57, in getMakr
    return JsonResponse({"result":util.StrToMakrDown(content)})
  File "I:\Icarus\Icarus-website\Util.py", line 62, in StrToMakrDown
    newStr = bleach.clean(newStr, bleach_whitelist.markdown_tags, bleach_whitelist.markdown_attrs)
AttributeError: module 'bleach_whitelist' has no attribute 'markdown_tags'
[31/Mar/2018 22:40:01] "POST /getMakr/ HTTP/1.1" 500 15906
```

**Comment by yika-aixi** [comment]
Send the wrong place
