### ISSUE TITLE
KeyError raised on something that looks like HTML, but isn't

### ISSUE THREAD

**Issue by erickpeirson** [mozilla/bleach#381]
```
Name: bleach
Version: 2.1.3
Summary: An easy safelist-based HTML-sanitizing tool.
Home-page: http://github.com/mozilla/bleach
Author: Will Kahn-Greene
Author-email: willkg@mozilla.com
License: Apache Software License
Location: ...
Requires: html5lib, six
```

I work with user-generated text that contains equations, and sometimes need to sanitize that text for display. Bleach provides a simple way to remove unwanted HTML (so thanks for that!). I recently noticed some cases where Bleach gets confused; in short it appears that Bleach thinks that a fragment of an equation is an HTML tag, [some things happen], and a KeyError is raised. 

Here's a real-life example that reproduces the problem:

```python
>>> import bleach
>>> bleach.clean("\\sum_{0<k_1<...<k_{n}<p}\\leg{p-k_{n}}{3} {(-1)^{k_{n}}\\over k_1... k_{n}}\\equiv\n  {lll} -{2^{n+1}+2\\over 6^{n+1}} p B_{p-n-1}({1\\over 3}) &\\pmod{p^2} &{if $n$ is odd} -{2^{n+1}+4\\over n6^n} B_{p-n}({1\\over 3}) &\\pmod{p} &{if $n$ is even}. $$ where $n$ is a positive integer and $p$ is prime such that $p>\\max(n+1,3)")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/bleach/__init__.py", line 99, in clean
    return cleaner.clean(text)
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/bleach/sanitizer.py", line 282, in clean
    return self.serializer.render(filtered)
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/html5lib/serializer.py", line 398, in render
    return "".join(list(self.serialize(treewalker)))
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/bleach/sanitizer.py", line 751, in serialize
    for stoken in super(BleachHTMLSerializer, self).serialize(treewalker, encoding):
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/html5lib/serializer.py", line 265, in serialize
    for token in treewalker:
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/bleach/sanitizer.py", line 439, in __iter__
    ret = self.sanitize_token(token)
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/bleach/sanitizer.py", line 479, in sanitize_token
    return self.disallowed_token(token)
  File "/Users/brp53/.local/share/virtualenvs/arxiv-search-sJgjMA70/lib/python3.6/site-packages/bleach/sanitizer.py", line 666, in disallowed_token
    name if ns is None else "%s:%s" % (prefixes[ns], name),
KeyError: '(-1)^{k_{n'
```

After some fiddling, it appears that this is the bit that Bleach thinks is HTML is:

```
"<p}\\leg{p-k_{n}}{3} {(-1)^{k_{n}}\\over k_1... k_{n}}\\equiv\n  {lll} -{2^{n+1}+2\\over 6^{n+1}} p B_{p-n-1}({1\\over 3}) &\\pmod{p^2} &{if $n$ is odd} -{2^{n+1}+4\\over n6^n} B_{p-n}({1\\over 3}) &\\pmod{p} &{if $n$ is even}. $$ where $n$ is a positive integer and $p$ is prime such that $p>"
```

I guess it's reasonable to think that might be HTML. But I would not have expected the ``KeyError``.

**Comment by erickpeirson** [comment]
Sounds great. Thanks for the quick reply.
