### ISSUE TITLE
AttributeError raised for a specific input

### ISSUE THREAD

**Issue by pv** [mozilla/bleach#402]
With bleach 3.0.0 (but not with 2.1.3), the following raises an error, which it probably should not do:
```
import sys, bleach
print(sys.version_info)
print(bleach.__version__)
content = '<img src="http://" alt=""id="" /></'
bleach.clean(content, tags=['img'])
```
Prints:
```
sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
3.0.0
Traceback (most recent call last):
  File "asd.py", line 5, in <module>
    bleach.clean(content, tags=['img'])
  File "/tmp/env/lib64/python3.7/site-packages/bleach/__init__.py", line 84, in clean
    return cleaner.clean(text)
  File "/tmp/env/lib64/python3.7/site-packages/bleach/sanitizer.py", line 169, in clean
    dom = self.parser.parseFragment(text)
  File "/tmp/env/lib64/python3.7/site-packages/bleach/_vendor/html5lib/html5parser.py", line 317, in parseFragment
    self._parse(stream, True, *args, **kwargs)
  File "/tmp/env/lib64/python3.7/site-packages/bleach/html5lib_shim.py", line 257, in _parse
    self.mainLoop()
  File "/tmp/env/lib64/python3.7/site-packages/bleach/_vendor/html5lib/html5parser.py", line 205, in mainLoop
    for token in self.normalizedTokens():
  File "/tmp/env/lib64/python3.7/site-packages/bleach/_vendor/html5lib/html5parser.py", line 264, in normalizedTokens
    for token in self.tokenizer:
  File "/tmp/env/lib64/python3.7/site-packages/bleach/html5lib_shim.py", line 130, in __iter__
    token_name = token['data'].lower().strip()
AttributeError: 'list' object has no attribute 'lower'
```
with
```
$ ./bin/pip list
Package      Version
------------ -------
bleach       3.0.0  
pip          18.0   
setuptools   40.4.3 
six          1.11.0 
webencodings 0.5.1  
```

**Comment by pv** [comment]
I guess this was #398

**Comment by willkg** [comment]
It'll go out in 3.0.1 soon.
