### ISSUE TITLE
Exception in bleach.linkify(): AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by levkowetz** [mozilla/bleach#406]
Bleach 3.0.0 raises an exception within linkify for input that bleach 2.1.4 deals with:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/__init__.py", line 131, in linkify
    return linker.linkify(text)
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/linkifier.py", line 151, in linkify
    dom = self.parser.parseFragment(text)
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/_vendor/html5lib/html5parser.py", line 317, in parseFragment
    self._parse(stream, True, *args, **kwargs)
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/html5lib_shim.py", line 257, in _parse
    self.mainLoop()
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/_vendor/html5lib/html5parser.py", line 205, in mainLoop
    for token in self.normalizedTokens():
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/_vendor/html5lib/html5parser.py", line 264, in normalizedTokens
    for token in self.tokenizer:
  File "/opt/home/henrik/trunk/local/lib/python2.7/site-packages/bleach/html5lib_shim.py", line 130, in __iter__
    token_name = token['data'].lower().strip()
AttributeError: 'list' object has no attribute 'lower'
```

The input that triggered this is attached.

[bleach-3.0.0-exception-input.txt](https://github.com/mozilla/bleach/files/2459035/bleach-3.0.0-exception-input.txt)

**Comment by willkg** [comment]
This is the same as issue #398. It's fixed in master tip and will go out in 3.0.1.

Thank you for the report!
